### PR TITLE
added other http methods along with std version

### PR DESCRIPTION
**Pull request by sidkhuntia**

### CODE REVIEW

**Comment by sidkhuntia** [comment]
@EwenQuim  can you review it ?

**Comment by EwenQuim** [comment]
Thank you very much! Can you add some tests in `mux_test.go` please?

**Comment by sidkhuntia** [comment]
Ok will do that

**Comment by sidkhuntia** [comment]
@EwenQuim  pls review it

**Comment by EwenQuim** [comment]
Perfect, thank you very much 👍🏼

**Comment by EwenQuim** [comment]
Fixes #13

**Pull request merged**
